In [9]:
s = input().split()

n = int(s[0])
m = int(s[1])

print(n)
print(m)


def print_matrix_2x(matrix_2x):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    """
    for row in matrix_2x:
        print(' '.join(map(str, row)))
    print()


matrix_2x = [[('*' if (row + col) % 2 else '.') for row in range(m)] for col in range(n)]
print_matrix_2x(matrix_2x)

3
4
. * . *
* . * .
. * . *


In [66]:
def print_matrix_2x(matrix_2x):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    """
    for row in matrix_2x:
        print(' '.join(map(str, row)))
    print()


# Элементы с индексами i и j, связанными соотношением i + j + 1 = n (или j = n - i - 1), где n — размерность матрицы, находятся на побочной диагонали.   

n = int(input())

matrix_2x = [[(1 if i + j + 1 == n else 2 if i + j >= n else '0') for i in range(n)] for j in range(n)]
print_matrix_2x(matrix_2x)

0 0 0 0 1
0 0 0 1 2
0 0 1 2 2
0 1 2 2 2
1 2 2 2 2


In [22]:
s = input().split()

n = int(s[0])
m = int(s[1])


def one_dimension_list_to_matrix(lst, n, m):
    """
    Преобразует одномерный список в список заданного размера.
    :param lst: Одномерный список.
    :return: Список заданного размера nxm.
    """
    if len(lst) != n * m:
        raise ValueError('Длина списка не соответствует размеру матрицы')

    matrix = []
    for i in range(n):
        row = []
        for j in range(m):
            row.append(lst[i * m + j])
        matrix.append(row)
    return matrix


def print_matrix_2x(matrix_2x):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    """
    for row in matrix_2x:
        print(' '.join(map(str, row)))
    print()


lst = [i + 1 for i in range(m * n)]
# print_matrix_2x(matrix_2x)
# print(lst)

matrix_2x = one_dimension_list_to_matrix(lst, n, m)
print_matrix_2x(matrix_2x)

1 2 3 4
5 6 7 8
9 10 11 12


In [63]:
s = input().split()

n = int(s[0])
m = int(s[1])
ljust_width = 3


def print_matrix_2x_with_ljust(matrix_2x, ljust_width):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    :param ljust_width: Ширина каждого элемента для выравнивания.
    """
    for row in matrix_2x:
        print(' '.join(str(item).ljust(ljust_width) for item in row))
    print()


"""Формируем список."""
lst = [i + 1 for i in range(n * m)]
# print(lst)

matrix_2x = []

for i in range(n):
    row = []
    for j in range(0, n * m, n):
        row.append(lst[j + i])
    matrix_2x.append(row)

# print(matrix_2x)
print_matrix_2x_with_ljust(matrix_2x, ljust_width)

1   4   7   10  13  16  19 
2   5   8   11  14  17  20 
3   6   9   12  15  18  21 


In [ ]:
n, m = [int(i) for i in input().split()]
matrix = [[0] * m for _ in range(n)]

for j in range(m):
    for i in range(n):
        matrix[i][j] = j * n + i + 1

for i in range(n):
    for j in range(m):
        print(str(matrix[i][j]).ljust(3), end=' ')
    print()

In [68]:
n = int(input())

matrix_2x = [[(1 if i == j or i + j + 1 == n else 0) for i in range(n)] for j in range(n)]


def print_matrix_2x_with_ljust(matrix_2x, ljust_width):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    :param ljust_width: Ширина каждого элемента для выравнивания.
    """
    for row in matrix_2x:
        print(' '.join(str(item).ljust(ljust_width) for item in row))
    print()


print_matrix_2x_with_ljust(matrix_2x, 3)

1   0   0   0   1  
0   1   0   1   0  
0   0   1   0   0  
0   1   0   1   0  
1   0   0   0   1  


In [70]:
# верх - i < j and i < n -1 -j
# низ - i > j and i > n -1 -j
# право - i < j and i > n -1 -j
# лево - i > j and i < n -1 -j

n = int(input())

matrix_2x = [
    [(1 if i == j or i + j + 1 == n or (i < j and i > n - 1 - j) or (i > j and i < n - 1 - j) else 0) for i in range(n)]
    for j in range(n)]


def print_matrix_2x_with_ljust(matrix_2x, ljust_width):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    :param ljust_width: Ширина каждого элемента для выравнивания.
    """
    for row in matrix_2x:
        print(' '.join(str(item).ljust(ljust_width) for item in row))
    print()


print_matrix_2x_with_ljust(matrix_2x, 3)

1   1   1   1  
0   1   1   0  
0   1   1   0  
1   1   1   1  


In [81]:
s = (5, 5)  #input().split()

n = int(s[0])
m = int(s[1])
ljust_width = 3


def print_matrix_2x_with_ljust(matrix_2x, ljust_width):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    :param ljust_width: Ширина каждого элемента для выравнивания.
    """
    for row in matrix_2x:
        print(' '.join(str(item).ljust(ljust_width) for item in row))
    print()


"""Формируем список."""
lst = [i + 1 for i in range(n * m)]
# print(lst)

matrix_2x = []

for i in range(n):
    row = []
    for j in range(m):
        row.append(lst[(i + j) % m])
    matrix_2x.append(row)

# print(matrix_2x)
print_matrix_2x_with_ljust(matrix_2x, ljust_width)

1   2   3   4   5  
2   3   4   5   1  
3   4   5   1   2  
4   5   1   2   3  
5   1   2   3   4  


In [99]:
s = (3, 5)  #input().split()

n = int(s[0])
m = int(s[1])
ljust_width = 3


def print_matrix_2x_with_ljust(matrix_2x, ljust_width):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    :param ljust_width: Ширина каждого элемента для выравнивания.
    """
    for row in matrix_2x:
        print(' '.join(str(item).ljust(ljust_width) for item in row))
    print()


"""Создание и заполнение списка."""
lst = [i + 1 for i in range(n * m)]
# print(lst)

"""Инициализируем матрицу."""
matrix_2x = []

"""Заполняем матрицу по условию."""
for i in range(n):
    row = []  # инициализируем ряд
    for j in range(m):
        row.append(lst[(i * m + j)])  # бьём список lst по рядам длиной m 
    if i % 2:  # каждый нечётный ряд переворачиваем
        row = row[::-1]
    matrix_2x.append(row)  # добавляем ряд в двумерную матрицу

# print(matrix_2x)
print_matrix_2x_with_ljust(matrix_2x, ljust_width)

1   2   3   4   5  
10  9   8   7   6  
11  12  13  14  15 


In [ ]:
n, m = [int(i) for i in input().split()]
matrix = [[0] * m for _ in range(n)]

for i in range(n):
    for j in range(m):
        matrix[i][j] = i * m + j + 1
    if i % 2:
        matrix[i].reverse()

for i in range(n):
    for j in range(m):
        print(str(matrix[i][j]).ljust(3), end=' ')
    print()

In [ ]:
a, b = map(int, input().split())

for i in range(a):
    print(*sorted(list(range(i * b + 1, i * b + b + 1)), reverse=i % 2))

In [ ]:
import numpy as np

"""Чтение входных данных."""
# n, m = [int(i) for i in input().split()]
row, col = map(int, input().split())

"""Создание и заполнение списка."""
lst = [i + 1 for i in range(row * col)]

"""Создание последовательности чисел и преобразование её в матрицу."""
matrix = np.array(  # np.array(...) преобразует список в массив numpy
    lst
).reshape(row, col)  # reshape(row, col) изменяет форму массива на матрицу с row строками и col столбцами

"""Вывод матрицы с переворотом нечётных строк."""
for i in range(row):
    if i % 2:  # каждый нечётный ряд переворачиваем
        print(*np.flip(matrix[i], axis=0))  # np.flip(..., axis=0) переворачивает строку по горизонтальной оси
    else:
        print(*matrix[i])

In [107]:
import numpy as np

n, m = (3, 5)  # map(int, input().split())
ljust_width = 3

"""Создаём пустой двумерный список."""
lst = [[0 for _ in range(m)] for _ in range(n)]
# print(lst)

element = 1
for i in range(n + m - 1):
    for r in range(n):
        for c in range(m):
            if r + c == i:
                lst[r][c] = element
                element += 1

matrix_2x = np.array(lst).reshape(n, m)
# print(matrix_2x)


def print_matrix_2x_with_ljust(matrix_2x, ljust_width):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    :param ljust_width: Ширина каждого элемента для выравнивания.
    """
    for row in matrix_2x:
        print(' '.join(str(item).ljust(ljust_width) for item in row))
    print()


print_matrix_2x_with_ljust(matrix_2x, ljust_width)

1 2 4 7 10
3 5 8 11 13
6 9 12 14 15


In [ ]:
# Принимаем параметры матрицы
n, m = map(int, input().split())
# Создаем скелет матрицы
matrix = [[0] * m for i in range(n)]
# Задаем отсчет с единицы
d = 1

for k in range(1, n + m):               # Цикл перебирающий сумму индексов в диагонали
    for i in range(n):                  # Перебираем строки
        for j in range(m):              # Перебираем столбцы
            if i + j + 1 == k:          # Выявляем ячейки, относящиеся к искомой диагонали
                matrix[i][j] = d        # Присваиваем обнаруженной ячейке порядковый номер
                d += 1                  # Обновляем счетчик

# Распечатываем полученную матрицу
for row in range(n):
    for col in range(m):
        print(str(matrix[row][col]).ljust(3), end=' ')
    print()

In [110]:
import numpy as np

n, m = (4, 5) # map(int, input().split())
ljust_width = 3

lst = [[0 for _ in range(n)]for _ in range(m)]
print(lst)
# Создание пустой матрицы
matrix = np.zeros((n, m), dtype=int)
print(matrix)

matrix_2x = np.array(lst).reshape(n, m)

def print_matrix_2x_with_ljust(matrix_2x, ljust_width):
    """
    Выводит двухмерный список в удобочитаемом формате.
    
    :param matrix_2x: Входная квадратная матрица (список списков).
    :param ljust_width: Ширина каждого элемента для выравнивания.
    """
    for row in matrix_2x:
        print(' '.join(str(item).ljust(ljust_width) for item in row))
    print()
    
print_matrix_2x_with_ljust(matrix_2x, ljust_width)

[[0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0], [0, 0, 0, 0]]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
0   0   0   0   0  
0   0   0   0   0  
0   0   0   0   0  
0   0   0   0   0  


In [ ]:
import numpy as np

# Ввод данных
n, m = map(int, input().split())

# Создание пустой матрицы
matrix = np.zeros((n, m), dtype=int)

# Инициализация начальных значений
directions = [(0, 1), (1, 0), (0, -1), (-1, 0)]  # Отличаются по порядку: вправо, вниз, влево, вверх.
direction_index = 0  # Начинаем с направления вправо
row, col = 0, 0  # Начальная позиция
value = 1

# Заполнение матрицы
for _ in range(n * m):
    matrix[row][col] = value
    value += 1
    
    # Вычисление следующей позиции
    new_row, new_col = row + directions[direction_index][0], col + directions[direction_index][1]
    
    # Проверка на границы и заполненные клетки
    if (0 <= new_row < n and 0 <= new_col < m and matrix[new_row][new_col] == 0):
        row, col = new_row, new_col
    else:
        # Меняем направление
        direction_index = (direction_index + 1) % 4
        row, col = row + directions[direction_index][0], col + directions[direction_index][1]

# Вывод матрицы
for i in range(n):
    for j in range(m):
        print(matrix[i][j], end=" ")
    print()